title: Welcome to my home, man!
description: > # this means to ignore newlines until "baseurl:"
 You've found OceanTiger's home! Take a look around and say hi if youre interested in working together.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oceantiger.net" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here
#future: true
# Author Settings
author: OceanTiger # add your name
author-img: artist.png # add your photo
about-author: Check out my links below. If you want to commission me, please send an email to commissions@oceantiger.net. Otherwise, check me out on Twitter (X ugh) and Bluesky!  # add description
social-twitter: OceanTiger11
#social-facebook: # add your Facebook handle
#social-github: # add your Github handle
#social-linkedin: # add your Linkedin handle
social-twitch: OceanTiger11
social-email: commissions@oceantiger.net # add your Email address
social-bluesky: oceantiger.bsky.social
#social-cashapp: $SusieCoffee # add your CashApp handle
#social-paypal: https://paypal.me/oceantiger # add your Paypal link 
social-ko-fi: https://ko-fi.com/oceantiger # add your Ko-fi link
# Disqus
#discus-identifier: OceanTiger # add your discus identifier

# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
